name: Environments
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: false
        description: Environment name
jobs:
  print:
    runs-on: ubuntu-latest
    environment: $ {{ inputs.environment-name }}
    env:
      ENV_USERNAME: ${{ vars.ENV_USERNAME }}
      ENV_PASSWORD: ${{ secrets.ENV_PASSWORD }}
    steps:
      - run: echo "${ENV_USERNAME}"
      - run: echo "${ENV_PASSWORD:0:1} ${ENV_PASSWORD#?}"
